"""Interactive setup wizard for ActionPulse.

Collects credentials and config via terminal prompts, generates:
  - ~/.config/actionpulse/env  (KEY=value, systemd-compatible)
  - configs/config.yaml        (copy of example with user values applied)

No text editor needed. Presentation is rich-powered (banner, step rules,
validated prompts, masked secrets, summary panel); it degrades to plain
text on non-TTY stdout, so piping scripted answers still works.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Callable, Optional

import typer
import yaml
from rich import box
from rich.console import Console
from rich.markup import escape
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table
from rich.text import Text

from digest_core.config import PROJECT_ROOT
from digest_core.setup_autodetect import CONF_HIGH, DetectedEnv, detect_environment

ENV_DIR = Path.home() / ".config" / "actionpulse"
ENV_PATH = ENV_DIR / "env"
CONFIG_EXAMPLE = PROJECT_ROOT / "configs" / "config.example.yaml"
CONFIG_USER = PROJECT_ROOT / "configs" / "config.yaml"
DEFAULT_CA_EXPORT_PATH = Path.home() / ".ssl" / "corp-ca.pem"
DEFAULT_CA_CHAIN_EXPORT_PATH = Path.home() / ".ssl" / "corp-ca-chain.pem"

TOTAL_STEPS = 6

console = Console()

# Brand gradient stops (cyan -> violet), used for the banner pulse line.
_GRAD_START = (34, 211, 238)
_GRAD_END = (167, 139, 250)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_existing_env() -> dict[str, str]:
    """Read existing env file into dict."""
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()
    return values


def _read_existing_config() -> dict:
    """Read existing user config.yaml into dict.

    Deliberately ignores config.example.yaml: its placeholder values
    (owa.corp-domain.ru, …) would otherwise shadow the defaults derived
    from the user's email on a fresh install.
    """
    if not CONFIG_USER.exists():
        return {}
    with open(CONFIG_USER, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _derive_from_email(email: str) -> dict[str, str]:
    """Derive EWS fields from corp email address.

    ivan.petrov@megacorp.ru ->
        user_login: ivan.petrov
        user_domain: megacorp.ru
        default_ews_endpoint: https://owa.megacorp.ru/EWS/Exchange.asmx
        aliases: ["Ivan", "Petrov", "ivan.petrov@megacorp.ru", "ivan.petrov"]
    """
    login, _, domain = email.partition("@")
    parts = re.split(r"[._-]", login)
    aliases = [p.capitalize() for p in parts if len(p) > 1]
    aliases.extend([email, login])

    return {
        "user_login": login,
        "user_domain": domain,
        "default_ews_endpoint": f"https://owa.{domain}/EWS/Exchange.asmx",
        "aliases": aliases,
    }


def _write_env_file(values: dict[str, str], ntlm_login_hint: Optional[str] = None) -> Path:
    """Write env file in systemd-compatible KEY=value format.

    ntlm_login_hint: detected machine (AD) login when it differs from the
    email local part — written as a commented override so the fix is at hand
    exactly where the user looks after an EWS auth failure.
    """
    ENV_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# ActionPulse environment — generated by 'python -m digest_core.cli setup'",
        "# Format: KEY=value (no export, no quotes) — works with systemd and bash",
        "",
        "# === Required ===",
        "",
    ]
    required_keys = [
        "EWS_PASSWORD",
        "EWS_USER_UPN",
        "EWS_ENDPOINT",
        "LLM_TOKEN",
        "LLM_ENDPOINT",
        "MM_WEBHOOK_URL",
    ]
    for key in required_keys:
        if key in values:
            lines.append(f"{key}={values[key]}")
    lines.append("")
    lines.append("# === Optional ===")
    lines.append("")
    lines.append("# DIGEST_CONFIG_PATH=/path/to/config.yaml")
    lines.append("# DIGEST_OUT_DIR=/custom/out")
    lines.append("# DIGEST_STATE_DIR=/custom/state")
    lines.append("# DIGEST_LOG_LEVEL=INFO")
    if ntlm_login_hint:
        lines.append("")
        lines.append("# NTLM-аутентификация EWS использует логин из email (user_login@domain).")
        lines.append("# Если EWS не пускает, попробуйте ваш AD-логин с этой машины:")
        lines.append(f"# EWS_USER_LOGIN={ntlm_login_hint}")
    lines.append("")

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(ENV_PATH, 0o600)
    return ENV_PATH


def _write_config_yaml(
    user_upn: str,
    ews_endpoint: str,
    llm_endpoint: str,
    derived: dict[str, str],
    verify_ca: Optional[str],
) -> Path:
    """Generate configs/config.yaml from example with user values applied."""
    if not CONFIG_EXAMPLE.exists():
        raise FileNotFoundError(f"Config example not found: {CONFIG_EXAMPLE}")

    with open(CONFIG_EXAMPLE, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    # Apply user values
    ews = config.get("ews", {})
    ews["endpoint"] = ews_endpoint
    ews["user_upn"] = user_upn
    ews["user_login"] = derived["user_login"]
    ews["user_domain"] = derived["user_domain"]
    ews["user_aliases"] = derived["aliases"]
    if verify_ca:
        ews["verify_ca"] = verify_ca
    else:
        ews.pop("verify_ca", None)
    config["ews"] = ews

    llm = config.get("llm", {})
    llm["endpoint"] = llm_endpoint
    config["llm"] = llm

    CONFIG_USER.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_USER, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return CONFIG_USER


def _test_mm_webhook(url: str, timeout: float = 5.0) -> tuple[bool, str]:
    """POST a fixed test message to the Mattermost incoming webhook.

    The only endpoint verifiable from outside the corp perimeter (ADR-012:
    Mattermost is reachable from everywhere). Returns (ok, detail); the URL
    is never logged.
    """
    try:
        import httpx

        resp = httpx.post(
            url,
            json={"text": "⌁ ActionPulse: webhook проверен — настройка завершена."},
            timeout=timeout,
        )
        if resp.status_code == 200:
            return True, "доставлено"
        return False, f"HTTP {resp.status_code}"
    except Exception as exc:  # noqa: BLE001 — any network failure is a soft result
        return False, type(exc).__name__


def _existing_ca_candidates(existing_cfg: dict) -> list[Path]:
    """Return prioritized CA path candidates from config + standard locations."""
    candidates: list[Path] = []

    cfg_ca = existing_cfg.get("ews", {}).get("verify_ca")
    if isinstance(cfg_ca, str) and cfg_ca.strip():
        candidates.append(Path(cfg_ca).expanduser())

    candidates.extend(
        [
            Path("/etc/ssl/corp-ca.pem"),
            Path.home() / ".ssl" / "corp-ca.pem",
            PROJECT_ROOT / "certs" / "corp-ca.pem",
        ]
    )
    return candidates


def _auto_detect_ca_path(existing_cfg: dict) -> Optional[str]:
    """Return first existing CA path from known candidates."""
    for path in _existing_ca_candidates(existing_cfg):
        if path.exists():
            return str(path)
    return None


def _guess_default_ca_alias(user_upn: str) -> Optional[str]:
    """Best-effort default Keychain alias for corp CA on macOS."""
    override = os.getenv("ACTIONPULSE_CA_CERT_NAME", "").strip()
    if override:
        return override

    domain = user_upn.partition("@")[2].lower()
    if "raiffeisen" in domain:
        return "AO Raiffeisenbank RootCA"
    return None


def _guess_default_intermediate_ca_alias(user_upn: str) -> Optional[str]:
    """Best-effort intermediate CA alias for corp chains on macOS."""
    domain = user_upn.partition("@")[2].lower()
    if "raiffeisen" in domain:
        return "AO Raiffeisenbank Issuing"
    return None


def _export_ca_from_keychain(cert_name: str) -> Optional[str]:
    """Read a CA certificate from macOS Keychain as PEM text."""
    try:
        result = subprocess.run(
            ["security", "find-certificate", "-c", cert_name, "-a", "-p"],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        return None

    pem = result.stdout.strip()
    if result.returncode != 0 or not pem or "BEGIN CERTIFICATE" not in pem:
        return None

    return pem


def _export_ca_chain_from_keychain(
    root_alias: str, output_path: Path, intermediate_alias: Optional[str] = None
) -> tuple[bool, int]:
    """Export root (+ optional intermediate) into a single PEM chain file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    certs: list[str] = []

    root_pem = _export_ca_from_keychain(root_alias)
    if not root_pem:
        return False, 0
    certs.append(root_pem.strip())

    if intermediate_alias:
        intermediate_pem = _export_ca_from_keychain(intermediate_alias)
        if intermediate_pem:
            certs.append(intermediate_pem.strip())

    output_path.write_text("\n\n".join(certs) + "\n", encoding="utf-8")
    return True, len(certs)


# ---------------------------------------------------------------------------
# Presentation helpers (pure where possible — covered by tests)
# ---------------------------------------------------------------------------


def _mask_secret(value: str, show_tail: int = 4) -> str:
    """Mask a secret for display: '••••abcd' (tail shown only for long values)."""
    if not value:
        return ""
    if show_tail and len(value) > show_tail * 3:
        return "••••" + value[-show_tail:]
    return "••••"


def _validate_email(value: str) -> Optional[str]:
    """Return error text for an invalid corp email, None when valid."""
    if "@" not in value or value.startswith("@") or value.endswith("@"):
        return "Email должен быть вида login@corp-domain.ru"
    if "." not in value.partition("@")[2]:
        return "Домен после @ выглядит неполным (нет точки)"
    return None


def _validate_url(value: str) -> Optional[str]:
    """Return error text for a non-http(s) URL, None when valid."""
    if not re.match(r"^https?://\S+$", value):
        return "Нужен полный URL, начинающийся с http:// или https://"
    return None


def _gradient_text(s: str) -> Text:
    """Brand gradient (cyan -> violet) across a string."""
    text = Text()
    n = max(len(s) - 1, 1)
    for i, ch in enumerate(s):
        t = i / n
        r = int(_GRAD_START[0] + (_GRAD_END[0] - _GRAD_START[0]) * t)
        g = int(_GRAD_START[1] + (_GRAD_END[1] - _GRAD_START[1]) * t)
        b = int(_GRAD_START[2] + (_GRAD_END[2] - _GRAD_START[2]) * t)
        text.append(ch, style=f"bold rgb({r},{g},{b})")
    return text


def _banner() -> None:
    title = _gradient_text("⌁ ActionPulse")
    title.append(" · настройка", style="bold default")
    body = Text.assemble(
        title,
        "\n",
        ("6 вопросов · секреты скрыты при вводе · повторный запуск безопасен", "dim"),
    )
    console.print()
    console.print(Panel(body, box=box.ROUNDED, border_style="cyan", padding=(0, 2), expand=False))
    console.print()


def _step(num: int, title: str, hint: Optional[str] = None) -> None:
    console.print()
    console.rule(f"[bold]Шаг {num}/{TOTAL_STEPS} · {title}[/]", align="left", style="dim cyan")
    if hint:
        console.print(f"[dim]{hint}[/]")


def _ask(
    label: str,
    *,
    default: Optional[str] = None,
    validate: Optional[Callable[[str], Optional[str]]] = None,
) -> str:
    """Prompt until non-empty and valid; Enter accepts the default."""
    while True:
        value = Prompt.ask(f"[bold cyan]{label}[/]", default=default, console=console)
        value = (value or "").strip()
        if not value:
            console.print("  [red]✗[/] Значение не может быть пустым")
            continue
        error = validate(value) if validate else None
        if error:
            console.print(f"  [red]✗[/] {error}")
            continue
        return value


def _ask_secret(label: str, *, existing: str = "") -> str:
    """Masked prompt with confirmation; Enter keeps the existing value on re-runs."""
    keep_hint = " [dim](Enter — оставить текущий)[/]" if existing else ""
    while True:
        value = Prompt.ask(
            f"[bold cyan]{label}[/]{keep_hint}",
            password=True,
            default="",
            show_default=False,
            console=console,
        ).strip()
        if not value:
            if existing:
                console.print("  [green]✓[/] Оставлен текущий секрет")
                return existing
            console.print("  [red]✗[/] Значение не может быть пустым")
            continue
        confirm = Prompt.ask(
            "[bold cyan]  Повторите для подтверждения[/]",
            password=True,
            default="",
            show_default=False,
            console=console,
        ).strip()
        if value == confirm:
            return value
        console.print("  [red]✗[/] Значения не совпали, попробуйте ещё раз")


def _ask_ca(existing_cfg: dict, user_upn: str) -> Optional[str]:
    """CA certificate flow: auto-detect -> Keychain export (macOS) -> manual path."""
    verify_ca: Optional[str] = _auto_detect_ca_path(existing_cfg)
    if verify_ca:
        console.print(f"  [green]✓[/] Автообнаружен CA-сертификат: [bold]{verify_ca}[/]")
        if Confirm.ask("[bold cyan]Использовать этот CA для EWS?[/]", default=True):
            return verify_ca
        verify_ca = None
    else:
        console.print("  [dim]CA-сертификат в стандартных путях не найден.[/]")
        if sys.platform == "darwin" and Confirm.ask(
            f"[bold cyan]Экспортировать CA chain из Keychain в "
            f"{DEFAULT_CA_CHAIN_EXPORT_PATH}?[/]",
            default=True,
        ):
            default_alias = _guess_default_ca_alias(user_upn)
            default_intermediate_alias = _guess_default_intermediate_ca_alias(user_upn)
            cert_name = _ask(
                "  Имя Root CA сертификата в Keychain",
                default=default_alias or "AO Raiffeisenbank RootCA",
            )
            intermediate_default = default_intermediate_alias or ""
            intermediate_hint = (
                f"(Enter — {intermediate_default})"
                if intermediate_default
                else "(Enter — пропустить)"
            )
            intermediate_alias: Optional[str] = (
                Prompt.ask(
                    f"[bold cyan]  Имя Intermediate CA[/] [dim]{intermediate_hint}[/]",
                    default=intermediate_default,
                    show_default=False,
                    console=console,
                ).strip()
                or None
            )

            with console.status("[cyan]Экспорт CA chain из Keychain…", spinner="dots"):
                ok, cert_count = _export_ca_chain_from_keychain(
                    cert_name,
                    DEFAULT_CA_CHAIN_EXPORT_PATH,
                    intermediate_alias=intermediate_alias,
                )
            if ok:
                verify_ca = str(DEFAULT_CA_CHAIN_EXPORT_PATH)
                console.print(
                    f"  [green]✓[/] CA chain экспортирован: {verify_ca} ({cert_count} cert)"
                )
            else:
                console.print("  [yellow]⚠[/] Не удалось экспортировать CA chain из Keychain.")

    if not verify_ca and Confirm.ask(
        "[bold cyan]Указать путь к CA-сертификату вручную?[/]", default=False
    ):
        verify_ca = _ask("  Путь к CA-сертификату (.pem)")
        if verify_ca and not Path(verify_ca).expanduser().exists():
            console.print(f"  [yellow]⚠[/] Файл не найден: {verify_ca} (сохраняю путь как есть)")
        elif verify_ca:
            verify_ca = str(Path(verify_ca).expanduser())
    return verify_ca


def _summary_table(env_values: dict[str, str], verify_ca: Optional[str]) -> Table:
    table = Table(box=box.SIMPLE, show_header=False, pad_edge=False)
    table.add_column(style="dim", min_width=18)
    table.add_column()
    table.add_row("Email (UPN)", env_values["EWS_USER_UPN"])
    table.add_row("EWS endpoint", env_values["EWS_ENDPOINT"])
    table.add_row("EWS пароль", _mask_secret(env_values["EWS_PASSWORD"], show_tail=0))
    table.add_row("LLM endpoint", env_values["LLM_ENDPOINT"])
    table.add_row("LLM токен", _mask_secret(env_values["LLM_TOKEN"]))
    table.add_row("MM webhook", env_values["MM_WEBHOOK_URL"])
    table.add_row("CA-сертификат", verify_ca or "[dim]— (системные доверенные)[/]")
    return table


def _print_detection(det: DetectedEnv) -> None:
    if not det.has_findings():
        console.print("[dim]Автообнаружение: ничего полезного не нашлось — спрошу всё явно.[/]")
        return
    lines = "\n".join(f"[green]✓[/] {escape(note)}" for note in det.notes)
    console.print(
        Panel(
            lines,
            title="[bold]Автообнаружение[/]",
            box=box.ROUNDED,
            border_style="dim cyan",
            expand=False,
        )
    )


def _merge_aliases(aliases: list[str], det: Optional[DetectedEnv]) -> list[str]:
    """Append detected real-name tokens and the machine login to the aliases.

    The email local part is not always name.surname, so the directory RealName
    is the only reliable alias source; the ranker lowercases aliases, so
    Title-case is enough.
    """
    if not det:
        return aliases
    extras: list[str] = []
    for token in (det.first_name, det.last_name):
        if token and len(token) > 1:
            extras.append(token.capitalize())
    if det.login:
        extras.append(det.login)
    merged = list(aliases)
    seen = {a.lower() for a in merged}
    for extra in extras:
        if extra.lower() not in seen:
            merged.append(extra)
            seen.add(extra.lower())
    return merged


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------


def run_setup(no_autodetect: bool = False) -> None:
    """Interactive setup: 6 questions, 0 text editors, auto-detected defaults."""
    try:
        _banner()

        det: Optional[DetectedEnv] = None
        existing_env = _read_existing_env()
        if not no_autodetect and not (
            existing_env.get("EWS_USER_UPN") and existing_env.get("EWS_ENDPOINT")
        ):
            with console.status(
                "[cyan]Автообнаружение: логин, имя, Keychain, домены сети…", spinner="dots"
            ):
                det = detect_environment()
            _print_detection(det)

        if _run_setup_flow(det=det, force_ask=False):
            return
        console.print()
        console.rule("[bold]Изменить ответы[/]", align="left", style="dim yellow")
        console.print("[dim]Пройдём вопросы заново; найденные значения — по умолчанию.[/]")
        if not _run_setup_flow(det=det, force_ask=True):
            console.print("[yellow]⚠ Отменено — файлы не изменены.[/]")
            raise typer.Exit(1)
    except (KeyboardInterrupt, EOFError):
        console.print("\n[yellow]⚠ Настройка прервана — файлы не изменены.[/]")
        raise typer.Exit(130)


def _run_setup_flow(det: Optional[DetectedEnv] = None, force_ask: bool = False) -> bool:
    """One pass over the questions; True when files were written, False on decline."""
    # Read existing values for defaults
    existing_env = _read_existing_env()
    existing_cfg = _read_existing_config()
    if existing_env:
        console.print(
            "[dim]Найдена существующая конфигурация — текущие значения "
            "подставлены как ответы по умолчанию.[/]"
        )

    det_upn = det.best_upn if det else None
    det_host = det.ews_host if det else None

    # ── 1. Corp email ──
    _step(1, "Корпоративный email", "Из него выведем EWS endpoint, логин и алиасы.")
    default_upn = (
        existing_env.get("EWS_USER_UPN")
        or existing_cfg.get("ews", {}).get("user_upn")
        or det_upn
        or None
    )
    if (
        not force_ask
        and det_upn
        and det is not None
        and det.upn_confidence == CONF_HIGH
        and not existing_env.get("EWS_USER_UPN")
        and _validate_email(det_upn) is None
    ):
        user_upn = det_upn
        console.print(
            f"  [green]✓[/] Автоматически: [bold]{user_upn}[/] "
            f"[dim](Keychain + имя + домен; поменять — «n» на финальном подтверждении)[/]"
        )
    else:
        user_upn = _ask(
            "Email (login@corp-domain.ru)", default=default_upn, validate=_validate_email
        )

    derived = _derive_from_email(user_upn)
    derived["aliases"] = _merge_aliases(derived["aliases"], det)
    console.print(
        f"  [green]✓[/] login [bold]{derived['user_login']}[/] · "
        f"домен [bold]{derived['user_domain']}[/]"
    )
    console.print(f"  [green]✓[/] алиасы: [dim]{', '.join(derived['aliases'])}[/]")

    # ── 2. EWS endpoint ──
    _step(2, "Exchange (EWS)", "Адрес EWS-сервиса корпоративной почты.")
    detected_ews = f"https://{det_host}/EWS/Exchange.asmx" if det_host else None
    default_ews = (
        existing_env.get("EWS_ENDPOINT")
        or existing_cfg.get("ews", {}).get("endpoint")
        or detected_ews
        or derived["default_ews_endpoint"]
    )
    if (
        not force_ask
        and detected_ews
        and det is not None
        and det.ews_endpoint_verified
        and not existing_env.get("EWS_ENDPOINT")
        and not existing_cfg.get("ews", {}).get("endpoint")
    ):
        ews_endpoint = detected_ews
        console.print(
            f"  [green]✓[/] Автоматически: [bold]{ews_endpoint}[/] [dim](хост из Keychain, DNS ✓)[/]"
        )
    else:
        ews_endpoint = _ask("EWS endpoint URL", default=default_ews, validate=_validate_url)

    # ── 3. EWS password ──
    _step(3, "Пароль Exchange", "Хранится только локально: ~/.config/actionpulse/env, chmod 600.")
    ews_password = _ask_secret("EWS пароль", existing=existing_env.get("EWS_PASSWORD", ""))

    # ── 4. LLM endpoint ──
    _step(4, "LLM Gateway", "Корпоративный LLM-шлюз (доступен только из корп-сети).")
    default_llm = (
        existing_env.get("LLM_ENDPOINT") or existing_cfg.get("llm", {}).get("endpoint") or None
    )
    llm_endpoint = _ask("LLM Gateway endpoint URL", default=default_llm, validate=_validate_url)

    # ── 5. LLM token ──
    _step(5, "Токен LLM Gateway", "Bearer-токен; в логи и конфиги в открытом виде не попадает.")
    llm_token = _ask_secret("LLM токен (Bearer)", existing=existing_env.get("LLM_TOKEN", ""))

    # ── 6. Mattermost webhook ──
    _step(6, "Mattermost", "Incoming webhook канала, куда доставлять дайджест.")
    default_mm = existing_env.get("MM_WEBHOOK_URL") or None
    mm_webhook = _ask("Mattermost webhook URL", default=default_mm, validate=_validate_url)

    # ── Optional: CA certificate (auto-first) ──
    console.print()
    console.rule("[bold]TLS · корпоративный CA[/]", align="left", style="dim cyan")
    console.print("[dim]Нужен, если корп-сертификаты не доверены системой (EWS за прокси).[/]")
    verify_ca = _ask_ca(existing_cfg, user_upn)

    # ── Review before writing ──
    env_values = {
        "EWS_PASSWORD": ews_password,
        "EWS_USER_UPN": user_upn,
        "EWS_ENDPOINT": ews_endpoint,
        "LLM_TOKEN": llm_token,
        "LLM_ENDPOINT": llm_endpoint,
        "MM_WEBHOOK_URL": mm_webhook,
    }
    console.print()
    console.print(
        Panel(
            _summary_table(env_values, verify_ca),
            title="[bold]Проверьте значения[/]",
            box=box.ROUNDED,
            border_style="cyan",
            expand=False,
        )
    )
    if not Confirm.ask("[bold cyan]Сохранить конфигурацию?[/]", default=True):
        return False

    # ── Write files ──
    # Machine (AD) login differing from the email local part is the classic
    # NTLM failure cause — leave the override at hand, commented out.
    ntlm_hint = None
    if det and det.login and det.login.lower() != derived["user_login"].lower():
        ntlm_hint = det.login

    with console.status("[cyan]Генерация файлов…", spinner="dots"):
        env_path = _write_env_file(env_values, ntlm_login_hint=ntlm_hint)
        config_path = _write_config_yaml(
            user_upn=user_upn,
            ews_endpoint=ews_endpoint,
            llm_endpoint=llm_endpoint,
            derived=derived,
            verify_ca=verify_ca,
        )
    console.print(f"  [green]✓[/] {env_path}  [dim](chmod 600)[/]")
    console.print(f"  [green]✓[/] {config_path}")

    # ── Load env into current process ──
    for key, val in env_values.items():
        os.environ[key] = val

    # ── Live check: Mattermost is the one endpoint reachable from anywhere ──
    # TTY-gated so scripted/piped runs keep a stable answer protocol.
    if sys.stdin.isatty() and Confirm.ask(
        "[bold cyan]Отправить тестовое сообщение в Mattermost?[/]", default=True
    ):
        with console.status("[cyan]Проверка webhook…", spinner="dots"):
            mm_ok, mm_detail = _test_mm_webhook(mm_webhook)
        if mm_ok:
            console.print("  [green]✓[/] Webhook работает — тестовое сообщение в канале")
        else:
            console.print(
                f"  [yellow]⚠[/] Webhook не ответил ({mm_detail}). Mattermost доступен и вне "
                f"корп-сети — проверьте URL (повторная настройка: повторите setup)."
            )

    # ── Summary ──
    next_steps = Text.assemble(
        ("Первый дайджест:\n\n", "bold"),
        ("  set -a && source ", "default"),
        (str(env_path), "cyan"),
        (" && set +a\n", "default"),
        ("  uv run python -m digest_core.cli diagnose\n", "default"),
        ("  uv run python -m digest_core.cli mm-ping\n", "default"),
        ("  uv run python -m digest_core.cli run --dry-run\n\n", "default"),
        ("EWS и LLM Gateway доступны только из корпоративной сети.", "dim"),
    )
    console.print()
    console.print(
        Panel(
            next_steps,
            title=_gradient_text("⌁ Готово"),
            box=box.ROUNDED,
            border_style="green",
            padding=(1, 2),
            expand=False,
        )
    )
    return True
