"""Interactive setup wizard for ActionPulse.

Collects credentials and config via terminal prompts, generates:
  - ~/.config/actionpulse/env  (KEY=value, systemd-compatible)
  - configs/config.yaml        (copy of example with user values applied)

No text editor needed. Presentation is rich-powered (banner, step rules,
validated prompts, masked secrets, summary panel); it degrades to plain
text on non-TTY stdout, so piping scripted answers still works.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Optional

import typer
import yaml
from rich import box
from rich.markup import escape
from rich.panel import Panel
from rich.prompt import Confirm, Prompt
from rich.table import Table
from rich.text import Text

from digest_core.config import PROJECT_ROOT
from digest_core.paths import data_home
from digest_core.ui import SPINNER, choose, get_console, gradient_text
from digest_core.setup_autodetect import (
    CONF_HIGH,
    DetectedEnv,
    _machine_login,
    detect_environment,
)

ENV_DIR = Path.home() / ".config" / "actionpulse"
ENV_PATH = ENV_DIR / "env"
LAUNCHER_PATH = Path.home() / ".local" / "bin" / "actionpulse"
CONFIG_EXAMPLE = PROJECT_ROOT / "configs" / "config.example.yaml"
CONFIG_USER = PROJECT_ROOT / "configs" / "config.yaml"
DEFAULT_CA_EXPORT_PATH = Path.home() / ".ssl" / "corp-ca.pem"
DEFAULT_CA_CHAIN_EXPORT_PATH = Path.home() / ".ssl" / "corp-ca-chain.pem"

TOTAL_STEPS = 7

console = get_console()

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_existing_env() -> dict[str, str]:
    """Read existing env file into dict."""
    values: dict[str, str] = {}
    if not ENV_PATH.exists():
        return values
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            values[key.strip()] = val.strip()
    return values


def _read_existing_config() -> dict:
    """Read existing user config.yaml into dict.

    Deliberately ignores config.example.yaml: its placeholder values
    (owa.corp-domain.ru, …) would otherwise shadow the defaults derived
    from the user's email on a fresh install.
    """
    if not CONFIG_USER.exists():
        return {}
    with open(CONFIG_USER, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def _derive_from_email(email: str) -> dict[str, str]:
    """Derive EWS fields from corp email address.

    ivan.petrov@megacorp.ru ->
        user_login: ivan.petrov   (FALLBACK only — see _resolve_ews_login)
        user_domain: megacorp.ru
        default_ews_endpoint: https://owa.megacorp.ru/EWS/Exchange.asmx
        aliases: ["Ivan", "Petrov", "ivan.petrov@megacorp.ru", "ivan.petrov"]

    NOTE: ``user_login`` here is the email local part and is only a last-resort
    fallback. EWS NTLM authenticates with the *machine* (AD) login from
    ``whoami`` — e.g. "ruapgr2" — which routinely differs from the email local
    part ("ruslan.pogorelov"). The wizard overrides it via _resolve_ews_login.
    """
    login, _, domain = email.partition("@")
    parts = re.split(r"[._-]", login)
    aliases = [p.capitalize() for p in parts if len(p) > 1]
    aliases.extend([email, login])

    return {
        "user_login": login,
        "user_domain": domain,
        "default_ews_endpoint": f"https://owa.{domain}/EWS/Exchange.asmx",
        "aliases": aliases,
    }


def _resolve_ews_login(
    existing_login: Optional[str], machine_login: Optional[str], email_local_part: str
) -> str:
    """EWS NTLM login: existing config wins, else the machine (AD) login from
    ``whoami`` (the correct NTLM identity, e.g. "ruapgr2"), else the email
    local part as a last resort."""
    return (existing_login or "").strip() or (machine_login or "").strip() or email_local_part


def _write_env_file(values: dict[str, str], ntlm_login_hint: Optional[str] = None) -> Path:
    """Write env file in systemd-compatible KEY=value format.

    ntlm_login_hint: detected machine (AD) login when it differs from the
    email local part — written as a commented override so the fix is at hand
    exactly where the user looks after an EWS auth failure.
    """
    ENV_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "# ActionPulse environment — generated by 'actionpulse setup'",
        "# Format: KEY=value (no export, no quotes) — works with systemd and bash",
        "",
        "# === Required ===",
        "",
    ]
    required_keys = [
        "EWS_PASSWORD",
        "EWS_USER_UPN",
        "EWS_ENDPOINT",
        "LLM_TOKEN",
        "LLM_ENDPOINT",
        "MM_WEBHOOK_URL",
    ]
    for key in required_keys:
        if key in values:
            lines.append(f"{key}={values[key]}")
    lines.append("")
    lines.append("# === Optional ===")
    lines.append("")
    lines.append("# DIGEST_CONFIG_PATH=/path/to/config.yaml")
    lines.append("# DIGEST_OUT_DIR=/custom/out")
    lines.append("# DIGEST_STATE_DIR=/custom/state")
    lines.append("# DIGEST_LOG_LEVEL=INFO")
    if ntlm_login_hint:
        lines.append("")
        lines.append("# EWS NTLM auth uses user_login@user_domain from config.yaml.")
        lines.append("# Override it here if EWS rejects the detected machine login:")
        lines.append(f"# EWS_USER_LOGIN={ntlm_login_hint}")
    lines.append("")

    ENV_PATH.write_text("\n".join(lines), encoding="utf-8")
    os.chmod(ENV_PATH, 0o600)
    return ENV_PATH


def _write_config_yaml(
    user_upn: str,
    ews_endpoint: str,
    llm_endpoint: str,
    derived: dict[str, str],
    verify_ca: Optional[str],
    report_language: str = "en",
) -> Path:
    """Generate configs/config.yaml from example with user values applied."""
    if not CONFIG_EXAMPLE.exists():
        raise FileNotFoundError(f"Config example not found: {CONFIG_EXAMPLE}")

    with open(CONFIG_EXAMPLE, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    # Apply user values
    ews = config.get("ews", {})
    ews["endpoint"] = ews_endpoint
    ews["user_upn"] = user_upn
    ews["user_login"] = derived["user_login"]
    ews["user_domain"] = derived["user_domain"]
    ews["user_aliases"] = derived["aliases"]
    if verify_ca:
        ews["verify_ca"] = verify_ca
    else:
        ews.pop("verify_ca", None)
    config["ews"] = ews

    llm = config.get("llm", {})
    llm["endpoint"] = llm_endpoint
    config["llm"] = llm

    report = config.get("report", {}) or {}
    report["language"] = report_language
    config["report"] = report

    CONFIG_USER.parent.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_USER, "w", encoding="utf-8") as f:
        yaml.dump(config, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return CONFIG_USER


def _test_mm_webhook(url: str, timeout: float = 5.0) -> tuple[bool, str]:
    """POST a fixed test message to the Mattermost incoming webhook.

    The only endpoint verifiable from outside the corp perimeter (ADR-012:
    Mattermost is reachable from everywhere). Returns (ok, detail); the URL
    is never logged.
    """
    try:
        import httpx

        resp = httpx.post(
            url,
            json={"text": "⌁ ActionPulse: webhook verified — setup complete."},
            timeout=timeout,
        )
        if resp.status_code == 200:
            return True, "delivered"
        return False, f"HTTP {resp.status_code}"
    except Exception as exc:  # noqa: BLE001 — any network failure is a soft result
        return False, type(exc).__name__


def _existing_ca_candidates(existing_cfg: dict) -> list[Path]:
    """Return prioritized CA path candidates from config + standard locations."""
    candidates: list[Path] = []

    cfg_ca = existing_cfg.get("ews", {}).get("verify_ca")
    if isinstance(cfg_ca, str) and cfg_ca.strip():
        candidates.append(Path(cfg_ca).expanduser())

    candidates.extend(
        [
            Path("/etc/ssl/corp-ca.pem"),
            Path.home() / ".ssl" / "corp-ca.pem",
            PROJECT_ROOT / "certs" / "corp-ca.pem",
        ]
    )
    return candidates


def _auto_detect_ca_path(existing_cfg: dict) -> Optional[str]:
    """Return first existing CA path from known candidates."""
    for path in _existing_ca_candidates(existing_cfg):
        if path.exists():
            return str(path)
    return None


def _guess_default_ca_alias(user_upn: str) -> Optional[str]:
    """Best-effort default Keychain alias for corp CA on macOS."""
    override = os.getenv("ACTIONPULSE_CA_CERT_NAME", "").strip()
    if override:
        return override

    domain = user_upn.partition("@")[2].lower()
    if "raiffeisen" in domain:
        return "AO Raiffeisenbank RootCA"
    return None


def _guess_default_intermediate_ca_alias(user_upn: str) -> Optional[str]:
    """Best-effort intermediate CA alias for corp chains on macOS."""
    domain = user_upn.partition("@")[2].lower()
    if "raiffeisen" in domain:
        return "AO Raiffeisenbank Issuing"
    return None


def _export_ca_from_keychain(cert_name: str) -> Optional[str]:
    """Read a CA certificate from macOS Keychain as PEM text."""
    try:
        result = subprocess.run(
            ["security", "find-certificate", "-c", cert_name, "-a", "-p"],
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        return None

    pem = result.stdout.strip()
    if result.returncode != 0 or not pem or "BEGIN CERTIFICATE" not in pem:
        return None

    return pem


def _export_ca_chain_from_keychain(
    root_alias: str, output_path: Path, intermediate_alias: Optional[str] = None
) -> tuple[bool, int]:
    """Export root (+ optional intermediate) into a single PEM chain file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    certs: list[str] = []

    root_pem = _export_ca_from_keychain(root_alias)
    if not root_pem:
        return False, 0
    certs.append(root_pem.strip())

    if intermediate_alias:
        intermediate_pem = _export_ca_from_keychain(intermediate_alias)
        if intermediate_pem:
            certs.append(intermediate_pem.strip())

    output_path.write_text("\n\n".join(certs) + "\n", encoding="utf-8")
    return True, len(certs)


# ---------------------------------------------------------------------------
# Global `actionpulse` launcher (next-steps hints must name a command that
# actually works — never `python -m digest_core.cli`)
# ---------------------------------------------------------------------------


@dataclass
class LauncherState:
    """What the finale may honestly promise about the `actionpulse` command."""

    use_command: bool  # `actionpulse …` is the primary next-steps form
    created: bool  # this wizard run wrote the shim (bare-checkout `make setup`)
    path_hint: bool  # the shim exists but ~/.local/bin is not on PATH


def _ensure_launcher() -> LauncherState:
    """Make sure the global `actionpulse` command exists; report its state.

    install.sh installs the shim on the curl-one-liner path; `make setup` from
    a bare checkout historically did not — so the finale used to advertise a
    command that did not exist. Mirror install.sh here: write the shim only
    when missing (an existing launcher, possibly pointing at another checkout,
    is never overwritten), exec through uv against this checkout.
    """
    if shutil.which("actionpulse"):
        return LauncherState(use_command=True, created=False, path_hint=False)
    if not shutil.which("uv"):
        # No uv to exec through — the module form is the only honest hint.
        return LauncherState(use_command=False, created=False, path_hint=False)
    created = False
    if not LAUNCHER_PATH.exists():
        try:
            LAUNCHER_PATH.parent.mkdir(parents=True, exist_ok=True)
            LAUNCHER_PATH.write_text(
                "#!/bin/sh\n"
                "# ActionPulse launcher — generated by 'actionpulse setup' (mirrors install.sh).\n"
                f'exec uv run --project "{PROJECT_ROOT}" python -m digest_core.cli "$@"\n',
                encoding="utf-8",
            )
            LAUNCHER_PATH.chmod(0o755)
            created = True
        except OSError:
            return LauncherState(use_command=False, created=False, path_hint=False)
    on_path = str(LAUNCHER_PATH.parent) in os.environ.get("PATH", "").split(os.pathsep)
    return LauncherState(use_command=True, created=created, path_hint=not on_path)


def _tilde(path: Path) -> str:
    """Render a path with the home prefix as `~` (display only, §6.2 paths)."""
    text = str(path)
    home = str(Path.home())
    return "~" + text[len(home) :] if text.startswith(home) else text


def _next_steps_text(state: LauncherState) -> Text:
    """Finale panel body: friendly `actionpulse` commands when the launcher
    works; the uv module form only as the no-launcher fallback. The CLI
    auto-loads ~/.config/actionpulse/env, so no `source` line in either form."""
    if state.use_command:
        parts: list[tuple[str, str]] = [
            ("First digest:\n\n", "bold"),
            (f"  {'actionpulse diagnose':<29}", "ap.accent"),
            ("check environment & config\n", "ap.dim"),
            (f"  {'actionpulse run --dry-run':<29}", "ap.accent"),
            ("safe first run (no LLM, no delivery)\n", "ap.dim"),
            (f"  {'actionpulse run':<29}", "ap.accent"),
            ("full pipeline + delivery\n", "ap.dim"),
            (f"  {'actionpulse':<29}", "ap.accent"),
            ("interactive menu · all options\n\n", "ap.dim"),
            (f"Secrets load automatically from {_tilde(ENV_PATH)} — no manual source.\n", "ap.dim"),
            (
                f"Digests, logs and state live under {_tilde(data_home())}/var"
                " (see: actionpulse paths).\n",
                "ap.dim",
            ),
        ]
        if state.path_hint:
            parts += [
                ("⚠ ~/.local/bin is not on your PATH yet — add it, then restart:\n", "ap.warn"),
                (
                    "  echo 'export PATH=\"$HOME/.local/bin:$PATH\"' >> ~/.zshrc && exec $SHELL\n",
                    "",
                ),
            ]
        parts.append(
            ("EWS and the LLM Gateway are reachable only from the corp network.", "ap.dim")
        )
        return Text.assemble(*parts)
    return Text.assemble(
        ("First digest (run from digest-core/):\n\n", "bold"),
        ("  uv run python -m digest_core.cli diagnose\n", ""),
        ("  uv run python -m digest_core.cli run --dry-run\n\n", ""),
        (f"Secrets load automatically from {_tilde(ENV_PATH)}.\n", "ap.dim"),
        ("EWS and the LLM Gateway are reachable only from the corp network.", "ap.dim"),
    )


# ---------------------------------------------------------------------------
# Presentation helpers (pure where possible — covered by tests)
# ---------------------------------------------------------------------------


def _mask_secret(value: str, show_tail: int = 4) -> str:
    """Mask a secret for display: '••••abcd' (tail shown only for long values)."""
    if not value:
        return ""
    if show_tail and len(value) > show_tail * 3:
        return "••••" + value[-show_tail:]
    return "••••"


def _validate_email(value: str) -> Optional[str]:
    """Return error text for an invalid corp email, None when valid."""
    if "@" not in value or value.startswith("@") or value.endswith("@"):
        return "Email must look like login@corp-domain.ru"
    if "." not in value.partition("@")[2]:
        return "The domain after @ looks incomplete (no dot)"
    return None


def _validate_url(value: str) -> Optional[str]:
    """Return error text for a non-http(s) URL, None when valid."""
    if not re.match(r"^https?://\S+$", value):
        return "A full URL starting with http:// or https:// is required"
    return None


def _banner() -> None:
    title = gradient_text("⌁ ActionPulse")
    title.append(" · setup", style="bold default")
    body = Text.assemble(
        title,
        "\n",
        ("7 questions · secrets hidden while typing · safe to re-run", "dim"),
    )
    console.print()
    console.print(
        Panel(body, box=box.ROUNDED, border_style="ap.accent", padding=(0, 2), expand=False)
    )
    console.print()


def _step(num: int, title: str, hint: Optional[str] = None) -> None:
    console.print()
    console.rule(f"[bold]Step {num}/{TOTAL_STEPS} · {title}[/]", align="left", style="ap.rule")
    if hint:
        console.print(f"[dim]{hint}[/]")


def _ask(
    label: str,
    *,
    default: Optional[str] = None,
    validate: Optional[Callable[[str], Optional[str]]] = None,
) -> str:
    """Prompt until non-empty and valid; Enter accepts the default."""
    while True:
        value = Prompt.ask(f"[ap.accent.bold]{label}[/]", default=default, console=console)
        value = (value or "").strip()
        if not value:
            console.print("  [ap.err]✗[/] The value cannot be empty")
            continue
        error = validate(value) if validate else None
        if error:
            console.print(f"  [ap.err]✗[/] {error}")
            continue
        return value


def _ask_secret(label: str, *, existing: str = "") -> str:
    """Masked prompt with confirmation; Enter keeps the existing value on re-runs."""
    keep_hint = " [dim](Enter — keep current)[/]" if existing else ""
    while True:
        value = Prompt.ask(
            f"[ap.accent.bold]{label}[/]{keep_hint}",
            password=True,
            default="",
            show_default=False,
            console=console,
        ).strip()
        if not value:
            if existing:
                console.print("  [ap.ok]✓[/] Kept the current secret")
                return existing
            console.print("  [ap.err]✗[/] The value cannot be empty")
            continue
        confirm = Prompt.ask(
            "[ap.accent.bold]  Repeat to confirm[/]",
            password=True,
            default="",
            show_default=False,
            console=console,
        ).strip()
        if value == confirm:
            return value
        console.print("  [ap.err]✗[/] The values did not match, try again")


def _ask_ca(existing_cfg: dict, user_upn: str) -> Optional[str]:
    """CA certificate flow: auto-detect -> Keychain export (macOS) -> manual path."""
    verify_ca: Optional[str] = _auto_detect_ca_path(existing_cfg)
    if verify_ca:
        console.print(f"  [ap.ok]✓[/] Auto-detected CA certificate: [bold]{verify_ca}[/]")
        if Confirm.ask("[ap.accent.bold]Use this CA for EWS?[/]", default=True):
            return verify_ca
        verify_ca = None
    else:
        console.print("  [dim]No CA certificate found in the standard paths.[/]")
        if sys.platform == "darwin" and Confirm.ask(
            f"[ap.accent.bold]Export the CA chain from Keychain to "
            f"{DEFAULT_CA_CHAIN_EXPORT_PATH}?[/]",
            default=True,
        ):
            default_alias = _guess_default_ca_alias(user_upn)
            default_intermediate_alias = _guess_default_intermediate_ca_alias(user_upn)
            cert_name = _ask(
                "  Root CA certificate name in Keychain",
                default=default_alias or "AO Raiffeisenbank RootCA",
            )
            intermediate_default = default_intermediate_alias or ""
            intermediate_hint = (
                f"(Enter — {intermediate_default})" if intermediate_default else "(Enter — skip)"
            )
            intermediate_alias: Optional[str] = (
                Prompt.ask(
                    f"[ap.accent.bold]  Intermediate CA name[/] [dim]{intermediate_hint}[/]",
                    default=intermediate_default,
                    show_default=False,
                    console=console,
                ).strip()
                or None
            )

            with console.status(
                "[ap.accent]Exporting the CA chain from Keychain…", spinner=SPINNER
            ):
                ok, cert_count = _export_ca_chain_from_keychain(
                    cert_name,
                    DEFAULT_CA_CHAIN_EXPORT_PATH,
                    intermediate_alias=intermediate_alias,
                )
            if ok:
                verify_ca = str(DEFAULT_CA_CHAIN_EXPORT_PATH)
                console.print(f"  [ap.ok]✓[/] CA chain exported: {verify_ca} ({cert_count} cert)")
            else:
                console.print("  [ap.warn]⚠[/] Failed to export the CA chain from Keychain.")

    if not verify_ca and Confirm.ask(
        "[ap.accent.bold]Provide a CA certificate path manually?[/]", default=False
    ):
        verify_ca = _ask("  Path to the CA certificate (.pem)")
        if verify_ca and not Path(verify_ca).expanduser().exists():
            console.print(
                f"  [ap.warn]⚠[/] File not found: {verify_ca} (keeping the path as given)"
            )
        elif verify_ca:
            verify_ca = str(Path(verify_ca).expanduser())
    return verify_ca


def _summary_table(
    env_values: dict[str, str],
    verify_ca: Optional[str],
    report_language: str = "en",
    ews_login: Optional[str] = None,
) -> Table:
    table = Table(box=box.SIMPLE, show_header=False, pad_edge=False)
    table.add_column(style="dim", min_width=18)
    table.add_column()
    table.add_row("Email (UPN)", env_values["EWS_USER_UPN"])
    if ews_login:
        table.add_row("EWS login (NTLM)", ews_login)
    table.add_row("EWS endpoint", env_values["EWS_ENDPOINT"])
    table.add_row("EWS password", _mask_secret(env_values["EWS_PASSWORD"], show_tail=0))
    table.add_row("LLM endpoint", env_values["LLM_ENDPOINT"])
    table.add_row("LLM token", _mask_secret(env_values["LLM_TOKEN"]))
    table.add_row("MM webhook", env_values["MM_WEBHOOK_URL"])
    table.add_row("Report language", report_language)
    table.add_row("CA certificate", verify_ca or "[dim]— (system trust store)[/]")
    return table


def _print_detection(det: DetectedEnv) -> None:
    if not det.has_findings():
        console.print("[dim]Autodetection: nothing useful found — asking everything explicitly.[/]")
        return
    lines = "\n".join(f"[ap.ok]✓[/] {escape(note)}" for note in det.notes)
    console.print(
        Panel(
            lines,
            title="[bold]Autodetection[/]",
            box=box.ROUNDED,
            border_style="ap.rule",
            expand=False,
        )
    )


def _merge_aliases(aliases: list[str], det: Optional[DetectedEnv]) -> list[str]:
    """Append detected real-name tokens and the machine login to the aliases.

    The email local part is not always name.surname, so the directory RealName
    is the only reliable alias source; the ranker lowercases aliases, so
    Title-case is enough.
    """
    if not det:
        return aliases
    extras: list[str] = []
    for token in (det.first_name, det.last_name):
        if token and len(token) > 1:
            extras.append(token.capitalize())
    if det.login:
        extras.append(det.login)
    merged = list(aliases)
    seen = {a.lower() for a in merged}
    for extra in extras:
        if extra.lower() not in seen:
            merged.append(extra)
            seen.add(extra.lower())
    return merged


# ---------------------------------------------------------------------------
# Main wizard
# ---------------------------------------------------------------------------


def run_setup(no_autodetect: bool = False) -> None:
    """Interactive setup: 7 questions, 0 text editors, auto-detected defaults."""
    try:
        _banner()

        det: Optional[DetectedEnv] = None
        existing_env = _read_existing_env()
        if not no_autodetect and not (
            existing_env.get("EWS_USER_UPN") and existing_env.get("EWS_ENDPOINT")
        ):
            with console.status(
                "[ap.accent]Autodetecting: login, name, Keychain, network domains…", spinner=SPINNER
            ):
                det = detect_environment()
            _print_detection(det)

        if _run_setup_flow(det=det, force_ask=False):
            return
        console.print()
        console.rule("[bold]Change answers[/]", align="left", style="ap.rule.attn")
        console.print(
            "[dim]Going through the questions again; detected values are the defaults.[/]"
        )
        if not _run_setup_flow(det=det, force_ask=True):
            console.print("[ap.warn]⚠ Cancelled — no files were changed.[/]")
            raise typer.Exit(1)
    except (KeyboardInterrupt, EOFError):
        console.print("\n[ap.warn]⚠ Setup interrupted — no files were changed.[/]")
        raise typer.Exit(130)


def _run_setup_flow(det: Optional[DetectedEnv] = None, force_ask: bool = False) -> bool:
    """One pass over the questions; True when files were written, False on decline."""
    # Read existing values for defaults
    existing_env = _read_existing_env()
    existing_cfg = _read_existing_config()
    if existing_env:
        console.print(
            "[dim]Existing configuration found — current values are "
            "pre-filled as the default answers.[/]"
        )

    det_upn = det.best_upn if det else None
    det_host = det.ews_host if det else None

    # ── 1. Corp email ──
    _step(1, "Corporate email", "Used to derive the EWS endpoint, login and aliases.")
    default_upn = (
        existing_env.get("EWS_USER_UPN")
        or existing_cfg.get("ews", {}).get("user_upn")
        or det_upn
        or None
    )
    if (
        not force_ask
        and det_upn
        and det is not None
        and det.upn_confidence == CONF_HIGH
        and not existing_env.get("EWS_USER_UPN")
        and _validate_email(det_upn) is None
    ):
        user_upn = det_upn
        console.print(
            f"  [ap.ok]✓[/] Automatic: [bold]{user_upn}[/] "
            f'[dim](Keychain + name + domain; to change it, answer "n" at the final confirmation)[/]'
        )
    else:
        user_upn = _ask(
            "Email (login@corp-domain.ru)", default=default_upn, validate=_validate_email
        )

    derived = _derive_from_email(user_upn)
    derived["aliases"] = _merge_aliases(derived["aliases"], det)

    # EWS NTLM login = the machine/AD login (whoami: "ruapgr2"), NOT the email
    # local part ("ruslan.pogorelov"). whoami is cheap and reliable even with
    # autodetection off; fall back to a prompt only if it is unavailable.
    machine_login = _machine_login()
    existing_login = existing_cfg.get("ews", {}).get("user_login") or existing_env.get(
        "EWS_USER_LOGIN"
    )
    if existing_login or machine_login:
        derived["user_login"] = _resolve_ews_login(
            existing_login, machine_login, derived["user_login"]
        )
    else:
        derived["user_login"] = _ask(
            "EWS login (NTLM username, e.g. ruapgr2)", default=derived["user_login"]
        )
    if machine_login and machine_login.lower() not in [a.lower() for a in derived["aliases"]]:
        derived["aliases"].append(machine_login)

    console.print(
        f"  [ap.ok]✓[/] EWS login [bold]{derived['user_login']}[/] "
        f"[dim](NTLM · machine login)[/] · domain [bold]{derived['user_domain']}[/]"
    )
    console.print(f"  [ap.ok]✓[/] email (UPN) [bold]{user_upn}[/]")
    console.print(f"  [ap.ok]✓[/] aliases: [dim]{', '.join(derived['aliases'])}[/]")

    # ── 2. EWS endpoint ──
    _step(2, "Exchange (EWS)", "Address of the corporate EWS mail service.")
    detected_ews = f"https://{det_host}/EWS/Exchange.asmx" if det_host else None
    default_ews = (
        existing_env.get("EWS_ENDPOINT")
        or existing_cfg.get("ews", {}).get("endpoint")
        or detected_ews
        or derived["default_ews_endpoint"]
    )
    if (
        not force_ask
        and detected_ews
        and det is not None
        and det.ews_endpoint_verified
        and not existing_env.get("EWS_ENDPOINT")
        and not existing_cfg.get("ews", {}).get("endpoint")
    ):
        ews_endpoint = detected_ews
        console.print(
            f"  [ap.ok]✓[/] Automatic: [bold]{ews_endpoint}[/] [dim](host from Keychain, DNS ✓)[/]"
        )
    else:
        ews_endpoint = _ask("EWS endpoint URL", default=default_ews, validate=_validate_url)

    # ── 3. EWS password ──
    _step(3, "Exchange password", "Stored locally only: ~/.config/actionpulse/env, chmod 600.")
    ews_password = _ask_secret("EWS password", existing=existing_env.get("EWS_PASSWORD", ""))

    # ── 4. LLM endpoint ──
    _step(4, "LLM Gateway", "Corporate LLM gateway (reachable only from the corp network).")
    default_llm = (
        existing_env.get("LLM_ENDPOINT") or existing_cfg.get("llm", {}).get("endpoint") or None
    )
    llm_endpoint = _ask("LLM Gateway endpoint URL", default=default_llm, validate=_validate_url)

    # ── 5. LLM token ──
    _step(5, "LLM Gateway token", "Bearer token; never written to logs or configs in plain form.")
    llm_token = _ask_secret("LLM token (Bearer)", existing=existing_env.get("LLM_TOKEN", ""))

    # ── 6. Mattermost webhook ──
    _step(6, "Mattermost", "Incoming webhook of the channel that receives the digest.")
    default_mm = existing_env.get("MM_WEBHOOK_URL") or None
    mm_webhook = _ask("Mattermost webhook URL", default=default_mm, validate=_validate_url)

    # ── 7. Report language ──
    _step(7, "Report language", "Digest output language; everything else stays English.")
    default_lang = existing_cfg.get("report", {}).get("language") or "en"
    if sys.stdin.isatty():
        report_language = choose(
            "Report language",
            # i18n-ok: a language names itself in its own language
            [("en", "English (default)"), ("ru", "Russian · Русский")],
            default_index=0 if default_lang == "en" else 1,
            console=console,
        )
    else:
        # Piped/scripted runs keep the line protocol stable.
        report_language = Prompt.ask(
            "[ap.accent.bold]Report language[/]",
            choices=["en", "ru"],
            default=default_lang,
            console=console,
        )

    # ── Optional: CA certificate (auto-first) ──
    console.print()
    console.rule("[bold]TLS · corporate CA[/]", align="left", style="ap.rule")
    console.print(
        "[dim]Needed when corp certificates are not trusted by the system (EWS behind a proxy).[/]"
    )
    verify_ca = _ask_ca(existing_cfg, user_upn)

    # ── Review before writing ──
    env_values = {
        "EWS_PASSWORD": ews_password,
        "EWS_USER_UPN": user_upn,
        "EWS_ENDPOINT": ews_endpoint,
        "LLM_TOKEN": llm_token,
        "LLM_ENDPOINT": llm_endpoint,
        "MM_WEBHOOK_URL": mm_webhook,
    }
    console.print()
    console.print(
        Panel(
            _summary_table(env_values, verify_ca, report_language, derived["user_login"]),
            title="[bold]Review the values[/]",
            box=box.ROUNDED,
            border_style="ap.accent",
            expand=False,
        )
    )
    if not Confirm.ask("[ap.accent.bold]Save the configuration?[/]", default=True):
        return False

    # ── Write files ──
    # user_login is now the machine/AD login. If the email local part differs,
    # leave it as a commented alternative in case NTLM wants that form instead.
    email_local_part = user_upn.partition("@")[0]
    ntlm_hint = (
        email_local_part if email_local_part.lower() != derived["user_login"].lower() else None
    )

    with console.status("[ap.accent]Writing files…", spinner=SPINNER):
        env_path = _write_env_file(env_values, ntlm_login_hint=ntlm_hint)
        config_path = _write_config_yaml(
            user_upn=user_upn,
            ews_endpoint=ews_endpoint,
            llm_endpoint=llm_endpoint,
            derived=derived,
            verify_ca=verify_ca,
            report_language=report_language,
        )
    console.print(f"  [ap.ok]✓[/] {env_path}  [dim](chmod 600)[/]")
    console.print(f"  [ap.ok]✓[/] {config_path}")

    # ── Load env into current process ──
    for key, val in env_values.items():
        os.environ[key] = val

    # ── Live check: Mattermost is the one endpoint reachable from anywhere ──
    # TTY-gated so scripted/piped runs keep a stable answer protocol.
    if sys.stdin.isatty() and Confirm.ask(
        "[ap.accent.bold]Send a test message to Mattermost?[/]", default=True
    ):
        with console.status("[ap.accent]Checking the webhook…", spinner=SPINNER):
            mm_ok, mm_detail = _test_mm_webhook(mm_webhook)
        if mm_ok:
            console.print("  [ap.ok]✓[/] Webhook works — the test message is in the channel")
        else:
            console.print(
                f"  [ap.warn]⚠[/] Webhook did not respond ({mm_detail}). Mattermost is reachable even "
                f"outside the corp network — check the URL (re-run setup to fix)."
            )

    # ── Summary: next steps speak `actionpulse`, never the module form ──
    launcher = _ensure_launcher()
    if launcher.created:
        console.print(
            f"  [ap.ok]✓[/] Command installed: [bold]actionpulse[/]  [ap.dim]({LAUNCHER_PATH})[/]"
        )
    console.print()
    console.print(
        Panel(
            _next_steps_text(launcher),
            title=gradient_text("⌁ Done"),
            box=box.ROUNDED,
            border_style="ap.ok",
            padding=(1, 2),
            expand=False,
        )
    )
    return True
